### ISSUE TITLE
Having problem running example inference

### ISSUE THREAD

**Issue by rnunziata** [NVIDIA/tacotron2#116]
trying to run using downloaded model....do not see other related issue here...so must ask. There is no other model or checkpoint available.

Passing in checkpoint:  waveglow_old.pt

```
> rjn@rjn-Oryx-Pro:~/projects/voice/waveglow$ python3 tacotron2/inference.py 
> /home/rjn/projects/voice/waveglow/tacotron2/layers.py:35: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
>   self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
> /home/rjn/projects/voice/waveglow/tacotron2/layers.py:15: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
>   gain=torch.nn.init.calculate_gain(w_init_gain))
> /usr/local/lib/python3.5/dist-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'glow_old.WaveGlow' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.5/dist-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.5/dist-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.5/dist-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'glow_old.WN' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> /usr/local/lib/python3.5/dist-packages/torch/serialization.py:434: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
>   warnings.warn(msg, SourceChangeWarning)
> Traceback (most recent call last):
>   File "tacotron2/inference.py", line 63, in <module>
>     model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})
> KeyError: 'state_dict'
```

and try again passing in checkpoint:  waveglow.pt after running covert utility on waveglow_old.pt

```

rjn@rjn-Oryx-Pro:~/projects/voice/waveglow$ gedit tacotron2/inference.py 
rjn@rjn-Oryx-Pro:~/projects/voice/waveglow$ python3 tacotron2/inference.py 
/home/rjn/projects/voice/waveglow/tacotron2/layers.py:35: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  self.conv.weight, gain=torch.nn.init.calculate_gain(w_init_gain))
/home/rjn/projects/voice/waveglow/tacotron2/layers.py:15: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  gain=torch.nn.init.calculate_gain(w_init_gain))
Traceback (most recent call last):
  File "tacotron2/inference.py", line 63, in <module>
    model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 538, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 850: ordinal not in range(128)

```

**Comment by rnunziata** [comment]
I was able to get past this by  replacing
```
#model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})

  with the following


model_state = model.state_dict()
pretrained_state = { k:v for k,v in model_state.items() if k in model_state and v.size() == model_state[k].size() }
model_state.update(pretrained_state)
model.load_state_dict(model_state)
```

I saved the  audio file with code below and it is not working.

```
audio = torch.autograd.Variable(spec_from_mel[:, :, :-1])
audio = audio.cpu().numpy()
audio = audio.astype('int16')
file_name = "myaudio"
audio_path = os.path.join(
        "./", "{}_synthesis.wav".format(file_name))
write(audio_path, hparams.sampling_rate, audio)

```

**Comment by rafaelvalle** [comment]
This issue should not be present with pytorch 1.0

**Comment by rnunziata** [comment]
python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.0.0
>>>

**Comment by rafaelvalle** [comment]
Note that our inference notebook does not this line
`model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})`

**Comment by EuphoriaCelestial** [comment]
> This issue should not be present with pytorch 1.0

I am using torch==1.0.0 and still have those issues

`/.local/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/.local/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/.local/lib/python3.6/site-packages/torch/serialization.py:657: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)`
