### ISSUE TITLE
TypeError: Cannot handle this data type

### ISSUE THREAD

**Issue by tsungruihon** [NVIDIA/tacotron2#149]
when i ran `python train.py --output_directory=taco_output/ --log_directory=log_dir`
it shown me the below error, seems the `tensorboardX` not work.

```
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
Epoch: 0
Train loss 0 76.131721 Grad Norm 14.724035 3.98s/it
Validation loss 0: 65.199608
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2428, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 400), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 284, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 242, in train
    hparams.distributed_run, rank)
  File "train.py", line 147, in validate
    logger.log_validation(reduced_val_loss, model, y, y_pred, iteration)
  File "/data/sh_tacotron2/logger.py", line 34, in log_validation
    iteration)
  File "/data/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 427, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/data/anaconda3/lib/python3.6/site-packages/tensorboardX/summary.py", line 216, in image
    image = make_image(tensor, rescale=rescale)
  File "/data/anaconda3/lib/python3.6/site-packages/tensorboardX/summary.py", line 254, in make_image
    image = Image.fromarray(tensor)
  File "/data/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2431, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```

**Comment by tsungruihon** [comment]
i downgrade the tensorboardX to `1.1` and then work.

**Comment by delgerdalai** [comment]
pip install -r requirements.txt

**Comment by batho2n** [comment]
But, If tensorboardX==1.1, following error message is occured
```
TypeError: Conflict register for file "tensorboard/compat/proto/resource_handle.proto": 
tensorboard.ResourceHandleProto is already defined in file "tensorboardX/src/resource_handle.proto". 
Please fix the conflict by adding package name on the proto file, or use different name for the 
duplication.
```

**Comment by nimamoradi** [comment]
i have same exact issue

**Comment by davislf2** [comment]
@batho2n did you resolve it? I have the same error of "Conflict register" in tensorboard and tensorboardX as well.

**Comment by batho2n** [comment]
@davislf2, I resolved the problem by removing tensorboard package

$ pip uninstall tensorboard

**Comment by bfs18** [comment]
add `dataformats='HWC'` argument to add_image function. The default value is 'CHW', which is not consistent with the image generated by `plot_alignment_to_numpy`.
