### ISSUE TITLE
ValueError: sampler option is mutually exclusive with shuffle Traceback 

### ISSUE THREAD

**Issue by deepconsc** [NVIDIA/tacotron2#168]
I'm getting shuffle error, with/without using conda enivronment, the CUDA version is 10.0, and tried on both - torch 0.4.1 & torch 1.0.0, but the same happens.

Anyone's willing to help, please?

**Comment by rafaelvalle** [comment]
Share the full error trace...

**Comment by deepconsc** [comment]
`FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing Distributed
Done initializing distributed
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=0']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=1']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=2']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=3']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=4']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=5']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=6']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=7']
`

**Comment by deepconsc** [comment]
`
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing Distributed
Done initializing distributed
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=0']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=1']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=2']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=3']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=4']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=5']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=6']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=7']
`

**Comment by deepconsc** [comment]
```

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing Distributed
Done initializing distributed
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 192, in train
    train_loader, valset, collate_fn = prepare_dataloaders(hparams)
  File "train.py", line 65, in prepare_dataloaders
    drop_last=True, collate_fn=collate_fn)
  File "/home/SDSU/anaconda3/envs/TARS/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 792, in __init__
    raise ValueError('sampler option is mutually exclusive with '
ValueError: sampler option is mutually exclusive with shuffle
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=0']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=1']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=2']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=3']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=4']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=5']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=6']
['train.py', '--output_directory=outdir', '--log_directory=logdir', '-c', 'tacotron2_statedict.pt', '--warm_start', '--hparams=distributed_run=True', '--n_gpus=8', '--group_name=group_2019_03_19-190837', '--rank=7']

```

**Comment by rafaelvalle** [comment]
Pull from master and try again. The DistributedSampler has it's own shuffling mechanism.

**Comment by deepconsc** [comment]
It works! Thank you.
