### ISSUE TITLE
"Length of all samples has to be greater than 0" error training model on Docker provided

### ISSUE THREAD

**Issue by Skriptotajs** [NVIDIA/tacotron2#169]
When I tried to train the model on LJ Speech dataset with the default parameters, I got the fallowing error:

> Saving model and optimizer state at iteration 0 to outdir/checkpoint_0
Train loss 1 37.975971 Grad Norm 20.044661 5.58s/it
Train loss 2 17.680506 Grad Norm 17.836054 4.90s/it
Train loss 3 10.451558 Grad Norm 16.734600 4.66s/it
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 220, in train
    y_pred = model(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/nvidia/tacotron2/model.py", line 516, in forward
    encoder_outputs = self.encoder(embedded_inputs, input_lengths)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/nvidia/tacotron2/model.py", line 183, in forward
    x, input_lengths, batch_first=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 57, in wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 124, in pack_padded_sequence
    data, batch_sizes = PackPadded.apply(input, lengths, batch_first)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/_functions/packing.py", line 12, in forward
    raise ValueError("Length of all samples has to be greater than 0, "
ValueError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0

**Comment by bruce-willis** [comment]
@Skriptotajs How have you managed to fix this? Having similar issue.
*Edit*: I had some empty texts in the dataset, dropping these samples solved the issue

**Comment by AnkurDebnath35** [comment]
I have search for empty texts and couldn't find any, but still getting the same error as a Runtime Error. Please help.

**Comment by rongpenl** [comment]
Check the files in filelists folder and make sure it is good.

**Comment by jazz215** [comment]
I am gettng the same error on custom dataset, couldnt find ant empty text, what do you mean by empty text, in filelists,
all file are format 

abc.wav|text
or
abc.pt|text

No empty text here.

**Comment by szymonpiech** [comment]
thanks! I've been changing the filelists for a couple of times and apparently an error must've sneak in as indeed there was two empty lines in the .txt! It fixed the problem for me.
