### ISSUE TITLE
Errors when training

### ISSUE THREAD

**Issue by ErnstTmp** [NVIDIA/tacotron2#196]
Hello, 
thanks for creating the Tacotron2!!!
I can not get the train.py to run.
When I install Pytorch 1.0.1.post2 (the current version) with Cuda 10.0 I get
 RuntimeError: code is too big

The nightly version produces the same result. Interestingly, the exception occurs while creating the mel spectrogram, see below.

and when I install Pytorch 1.0.0 I get 

RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

I am running on 1 Titan RTX with Cuda Driver 10.0, and I did not change the standard parameters of the Tacotron

I also tried Cuda 9.0 with the current release, Cuda 9.0 with the old release etc, but that did not change the picture. I am installing unsing Conda / Python 3.6 on an Ubuntu 18.0.4 box.

Thanks for your help,
Ernst

Exception: 
```
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 208, in train
    for i, batch in enumerate(train_loader):
  File "/home/adamriese/anaconda3/envs/t2t/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/adamriese/anaconda3/envs/t2t/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/adamriese/anaconda3/envs/t2t/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/adamriese/anaconda3/envs/t2t/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/adamriese/aiprojects/nvidia-tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/home/adamriese/aiprojects/nvidia-tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/home/adamriese/aiprojects/nvidia-tacotron2/data_utils.py", line 46, in get_mel
    melspec = self.stft.mel_spectrogram(audio_norm)
  File "/home/adamriese/aiprojects/nvidia-tacotron2/layers.py", line 76, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "/home/adamriese/aiprojects/nvidia-tacotron2/stft.py", line 95, in transform
    padding=0)
RuntimeError: code is too big

```

**Comment by ErnstTmp** [comment]
I tried Pytorch 1.1.0 now and have the same error still.

**Comment by kannadaraj** [comment]
@ErnstTmp I had the same issue. I tried everything i could.  But the problem persisted. I finally figured that the problem is conda environment. For some reason when i install all packages (especially pytorch) using conda it is giving this error. I did the same steps using normal virtualenv and pip install all packages.. It worked fine.. Try that.

Surely this may not solve the underlying issue but a sure work-around...

**Comment by rafaelvalle** [comment]
There's seems to be some CPU memory issue
Try this hack:
```
        forward_transform = F.conv1d(
            input_data.cuda(),
            Variable(self.forward_basis.cuda(), requires_grad=False).cuda(),
            stride=self.hop_length,
            padding=0).cpu()
```

**Comment by Yudonggeun** [comment]
Try it. But Errorrrr

~~~
s/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/modeep/Documents/GitHub/tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/home/modeep/Documents/GitHub/tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/home/modeep/Documents/GitHub/tacotron2/data_utils.py", line 46, in get_mel
    melspec = self.stft.mel_spectrogram(audio_norm)
  File "/home/modeep/Documents/GitHub/tacotron2/layers.py", line 76, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "/home/modeep/Documents/GitHub/tacotron2/stft.py", line 93, in transform
    Variable(self.forward_basis.cuda(), requires_grad=False).cuda(),
RuntimeError: CUDA error: initialization error
~~~

**Comment by vikrantsharma7** [comment]
Try using `num_workers=0` in both train and valid DataLoaders in train.py, along with Rafael's hack above.

**Comment by Yudonggeun** [comment]
Wow, Thank you!!

**Comment by rafaelvalle** [comment]
Note that by using `num_workers=0` the data will be loaded in the main process only, no sub-processes.
