### ISSUE TITLE
 error: dist.broadcast(p, 0)

### ISSUE THREAD

**Issue by chen849157649** [NVIDIA/tacotron2#205]
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 179, in train
    model = apply_gradient_allreduce(model)
  File "/home/chengt1/workspace/tacotron2/distributed.py", line 135, in apply_gradient_allreduce
    dist.broadcast(p, 0)
  File "/home/chengt1/anaconda3/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 737, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: CUDA error: unknown error (record at /opt/conda/conda-bld/pytorch_1544174967633/work/aten/src/ATen/cuda/CUDAEvent.h:87)

brother! could you help me? thank you

**Comment by rafaelvalle** [comment]
You seem to be running distributed training. Do you have multiple GPUs and are they available?

**Comment by chen849157649** [comment]
> You seem to be running distributed training. Do you have multiple GPUs and are they available?

yes, multiple GPUs are available，but this project running distributed training, CUDA error: in apply_gradient_allreduce   dist.broadcast(p, 0)

**Comment by rafaelvalle** [comment]
Can you run with a single GPU?

**Comment by Shubhanshu07** [comment]
I am also getting this error I am able to run on the single GPU but not on multiple GPUs

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
