### ISSUE TITLE
Failed to interpret wav file as pickle.

### ISSUE THREAD

**Issue by idharmateja** [NVIDIA/tacotron2#22]
I am getting following error when I ran the train script.
I don't see any preprocessing step to convert WAV to pickle files in README. Any leads ?

Traceback (most recent call last):
  File "train.py", line 288, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 206, in train
    for i, batch in enumerate(train_loader):
  File "/nfs_home/dvooturi/venvs/tacotron/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/nfs_home/dvooturi/venvs/tacotron/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
OSError: Traceback (most recent call last):
  File "/nfs_home/dvooturi/venvs/tacotron/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: unpickling stack underflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs_home/dvooturi/venvs/tacotron/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/nfs_home/dvooturi/venvs/tacotron/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/nfs_home/dvooturi/projects/tts/tacotron2/data_utils.py", line 60, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/nfs_home/dvooturi/projects/tts/tacotron2/data_utils.py", line 36, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/nfs_home/dvooturi/projects/tts/tacotron2/data_utils.py", line 48, in get_mel
    melspec = torch.from_numpy(np.load(filename))
  File "/nfs_home/dvooturi/venvs/tacotron/lib/python3.6/site-packages/numpy/lib/npyio.py", line 431, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'LJSpeech-1.1/wavs/LJ038-0104.wav' as a pickle

**Comment by rafaelvalle** [comment]
You set `load_mel_from_disk=True` but you're trying to load WAV files.

**Comment by rafaelvalle** [comment]
Closing. Please re-open if there are further issues.
