### ISSUE TITLE
Install instructions for baremetal linux that don't suck? 

### ISSUE THREAD

**Issue by danindiana** [NVIDIA/tacotron2#255]
This is an issue with every instance of tensorflow + nvidia cuda. Why do all the install instructions fail and fail and fail again? Version control and dependencies are too complex, correcting versions in one area ends up breaking some in others. No one is going to use this software if the only people using it managed to install it by mistake. There has to be a better way. 

So this is a shout out to anyone who has installed tacotron on an Ubuntu 18.04 with an Nvidia gpu. Any help? Does anyone have a step-by-step bash history they wouldn't mind sharing? Thanks!

oh and if you want some error code see below: 

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

(venv3) merlin@merlin-desktop:~/opfoghorn/tacotron2$ python3 train.py --output_directory=/home/merlin/opfoghorn/tacotron2/outputdir/ --log_directory=/home/merlin/opfoghorn/tacotron2/logoutdir/
/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from hparams import create_hparams
  File "/home/merlin/opfoghorn/tacotron2/hparams.py", line 1, in <module>
    import tensorflow as tf
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/__init__.py", line 35, in <module>
    from tensorflow._api.v1 import compat
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/_api/v1/compat/__init__.py", line 22, in <module>
    from tensorflow._api.v1.compat import v2
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorflow/_api/v1/compat/v2/__init__.py", line 303, in <module>
    from tensorboard.summary._tf import summary
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 24, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorboard/plugins/audio/summary.py", line 36, in <module>
    from tensorboard.plugins.audio import metadata
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorboard/plugins/audio/metadata.py", line 21, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 15, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 15, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n.tensorboard/compat/proto/resource_handle.proto\x12\x0btensorboard\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
  File "/home/merlin/opfoghorn/apex/venv3/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 879, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/compat/proto/resource_handle.proto":
  tensorboard.ResourceHandleProto.device: "tensorboard.ResourceHandleProto.device" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.container: "tensorboard.ResourceHandleProto.container" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.name: "tensorboard.ResourceHandleProto.name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.hash_code: "tensorboard.ResourceHandleProto.hash_code" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.maybe_type_name: "tensorboard.ResourceHandleProto.maybe_type_name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto: "tensorboard.ResourceHandleProto" is already defined in file "tensorboardX/src/resource_handle.proto".

pip list
Package                      Version            
---------------------------- -------------------
absl-py                      0.7.1              
apex                         0.1                
asn1crypto                   0.24.0             
astor                        0.8.0              
atomicwrites                 1.3.0              
attrs                        19.1.0             
audioread                    2.1.8              
certifi                      2018.1.18          
chardet                      3.0.4              
command-not-found            0.3                
cryptography                 2.1.4              
cupshelpers                  1.0                
cxxfilt                      0.2.0              
cycler                       0.10.0             
decorator                    4.4.0              
defer                        1.0.6              
distro-info                  0.18ubuntu0.18.04.1
gast                         0.2.2              
google-pasta                 0.1.7              
grpcio                       1.23.0             
h5py                         2.9.0              
httplib2                     0.9.2              
idna                         2.6                
importlib-metadata           0.19               
inflect                      0.2.5              
joblib                       0.13.2             
Keras-Applications           1.0.8              
Keras-Preprocessing          1.1.0              
keyring                      10.6.0             
keyrings.alt                 3.0                
language-selector            0.1                
launchpadlib                 1.10.6             
lazr.restfulclient           0.13.5             
lazr.uri                     1.0.3              
librosa                      0.6.0              
lightdm-gtk-greeter-settings 1.2.2              
llvmlite                     0.29.0             
Markdown                     3.1.1              
matplotlib                   2.1.0              
more-itertools               7.2.0              
netifaces                    0.10.4             
numba                        0.45.1             
numpy                        1.17.0             
oauth                        1.0.1              
packaging                    19.1               
pexpect                      4.2.1              
Pillow                       5.1.0              
pip                          19.2.2             
pluggy                       0.12.0             
protobuf                     3.9.1              
py                           1.8.0              
pycairo                      1.16.2             
pycrypto                     2.6.1              
pycups                       1.9.73             
pygobject                    3.26.1             
pyparsing                    2.4.2              
pytest                       5.1.1              
python-apt                   1.6.4              
python-dateutil              2.6.1              
python-debian                0.1.32             
pytz                         2019.2             
pyxdg                        0.25               
PyYAML                       5.1.2              
reportlab                    3.4.0              
requests                     2.18.4             
requests-unixsocket          0.1.5              
resampy                      0.2.2              
scikit-learn                 0.21.3             
scipy                        1.0.0              
screen-resolution-extra      0.0.0              
SecretStorage                2.3.1              
setuptools                   41.2.0             
simplejson                   3.13.2             
six                          1.11.0             
tensorboard                  1.14.0             
tensorboardX                 1.1                
tensorflow                   1.14.0             
tensorflow-estimator         1.14.0             
termcolor                    1.1.0              
torch                        1.2.0              
torchvision                  0.4.0              
tqdm                         4.34.0             
ubuntu-drivers-common        0.0.0              
ufw                          0.36               
Unidecode                    1.0.22             
urllib3                      1.22               
usb-creator                  0.3.3              
vboxapi                      1.0                
virtualenv                   16.7.3             
wadllib                      1.3.2              
wcwidth                      0.1.7              
Werkzeug                     0.15.5             
wheel                        0.33.6             
wrapt                        1.11.2             
xkit                         0.0.0              
zipp                         0.5.2              
zope.interface               4.3.2   

nvidia-smi
Thu Aug 22 22:25:47 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M4000        Off  | 00000000:09:00.0  On |                  N/A |
| 46%   34C    P8    12W / 120W |     71MiB /  8126MiB |     10%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 105...  Off  | 00000000:41:00.0  On |                  N/A |
| 29%   29C    P8    N/A /  75W |    226MiB /  4032MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1909      G   /usr/lib/xorg/Xorg                            50MiB |
|    1      1909      G   /usr/lib/xorg/Xorg                           128MiB |
|    1      5236      G   ...quest-channel-token=9884100064965360199    94MiB |
+-----------------------------------------------------------------------------+

**Comment by ryangrahamnc** [comment]
I was having that tensorboard proto error too (after a ton of other errors one at a time). Ended up forcing it to a newer version and it worked: 
`pip install tensorboardX==1.8`

**Comment by danindiana** [comment]
Thanks! Will give that a try.

**Comment by Clement-Hui** [comment]
See issue #257

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
