### ISSUE TITLE
tensorboard causes error

### ISSUE THREAD

**Issue by Clement-Hui** [NVIDIA/tacotron2#257]
Traceback (most recent call last):
  File "/media/clement/Shared DATA/Programming/PythonProjects/CUHK projects/tacotron2/train.py", line 17, in <module>
    from hparams import create_hparams
  File "/media/clement/Shared DATA/Programming/PythonProjects/CUHK projects/tacotron2/hparams.py", line 1, in <module>
    import tensorflow as tf
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow._api.v1 import compat
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorflow/_api/v1/compat/__init__.py", line 22, in <module>
    from tensorflow._api.v1.compat import v2
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorflow/_api/v1/compat/v2/__init__.py", line 303, in <module>
    from tensorboard.summary._tf import summary
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 25, in <module>
    from tensorboard.summary import v1
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorboard/summary/v1.py", line 24, in <module>
    from tensorboard.plugins.audio import summary as _audio_summary
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorboard/plugins/audio/summary.py", line 36, in <module>
    from tensorboard.plugins.audio import metadata
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorboard/plugins/audio/metadata.py", line 21, in <module>
    from tensorboard.compat.proto import summary_pb2
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorboard/compat/proto/summary_pb2.py", line 15, in <module>
    from tensorboard.compat.proto import tensor_pb2 as tensorboard_dot_compat_dot_proto_dot_tensor__pb2
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorboard/compat/proto/tensor_pb2.py", line 15, in <module>
    from tensorboard.compat.proto import resource_handle_pb2 as tensorboard_dot_compat_dot_proto_dot_resource__handle__pb2
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/tensorboard/compat/proto/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n.tensorboard/compat/proto/resource_handle.proto\x12\x0btensorboard\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
  File "/home/clement/.conda/envs/ML/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 879, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool!
Invalid proto descriptor for file "tensorboard/compat/proto/resource_handle.proto":
  tensorboard.ResourceHandleProto.device: "tensorboard.ResourceHandleProto.device" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.container: "tensorboard.ResourceHandleProto.container" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.name: "tensorboard.ResourceHandleProto.name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.hash_code: "tensorboard.ResourceHandleProto.hash_code" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto.maybe_type_name: "tensorboard.ResourceHandleProto.maybe_type_name" is already defined in file "tensorboardX/src/resource_handle.proto".
  tensorboard.ResourceHandleProto: "tensorboard.ResourceHandleProto" is already defined in file "tensorboardX/src/resource_handle.proto".

code only work if I uninstall tensorboard, and run the code, and install tensorboard again. Is there a solution to this? Thank you

**Comment by Clement-Hui** [comment]
I am not sure. It also happened whenever I use tensorboardX. Maybe it is a problem with pytorch version? However, I install pytorch 1.0 and it didn't work as well.

**Comment by nathanfigmvnu** [comment]
> `tensorboard==1.14.0 tensorboardX==1.8` 
These are the exact versions I am using, same result. Any other dependencies that might have new versions?

**Comment by figuernd** [comment]
> `tensorboard==1.14.0 tensorboardX==1.8`
These are the exact versions I am using, same result. Any other dependencies that might have changed?

**Comment by figuernd** [comment]
Okay, I noticed a pull request for a fix which changed the requirements files to specify some older dependency versions, and I changed my dependencies accordingly: https://github.com/NVIDIA/tacotron2/pull/240/commits/0f348efed49dea2a3a40e6f318862f0d34264400
Also downgraded to PyTorch 1.0.1.

**Comment by Clement-Hui** [comment]
Thank you. This worked very well. Closing this issue
