### ISSUE TITLE
Exception: loss is NaN ?

### ISSUE THREAD

**Issue by danindiana** [NVIDIA/tacotron2#258]
Running    torch                        1.2.0

Anyone else get this error? 

$python3 train.py -m Tacotron2 --epochs 100 -lr 0.05 -bs 16 --output_directory=/home/merlin/opfoghorn/tacotron2/outputdir/ --log-file=nvlog.json
:::NVLOGv0.2.2 Tacotron2_PyT 1566787699.469461679 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:279) run_start
:::NVLOGv0.2.2 Tacotron2_PyT 1566787699.482044220 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) cpu_info: {"num": 48, "name": "AMD Ryzen Threadripper 2970WX 24-Core Processor"}
:::NVLOGv0.2.2 Tacotron2_PyT 1566787699.491433620 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) mem_info: {"ram": "62G"}
:::NVLOGv0.2.2 Tacotron2_PyT 1566787699.636062145 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "430.40", "num": 2, "name": ["Quadro M4000", "GeForce GTX 1050 Ti"], "mem": ["8126 MiB", "4032 MiB"]}
:::NVLOGv0.2.2 Tacotron2_PyT 1566787699.639187098 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) args: {"output_directory": "/home/merlin/opfoghorn/tacotron2/outputdir/", "dataset_path": "./", "model_name": "Tacotron2", "log_file": "nvlog.json", "phrase_path": null, "waveglow_checkpoint": null, "tacotron2_checkpoint": null, "anneal_steps": null, "anneal_factor": 0.1, "epochs": 100, "epochs_per_checkpoint": 50, "seed": 1234, "dynamic_loss_scaling": true, "amp_run": false, "cudnn_enabled": false, "cudnn_benchmark": false, "disable_uniform_initialize_bn_weight": false, "use_saved_learning_rate": false, "learning_rate": 0.05, "weight_decay": 1e-06, "grad_clip_thresh": 1.0, "batch_size": 4, "grad_clip": 5.0, "load_mel_from_disk": false, "training_files": "filelists/ljs_audio_text_train_filelist.txt", "validation_files": "filelists/ljs_audio_text_val_filelist.txt", "text_cleaners": ["english_cleaners"], "max_wav_value": 32768.0, "sampling_rate": 22050, "filter_length": 1024, "hop_length": 256, "win_length": 1024, "mel_fmin": 0.0, "mel_fmax": 8000.0, "rank": 0, "world_size": 1, "dist_url": "tcp://localhost:23456", "group_name": "group_name", "dist_backend": "nccl", "mask_padding": false, "n_mel_channels": 80, "n_symbols": 148, "symbols_embedding_dim": 512, "encoder_kernel_size": 5, "encoder_n_convolutions": 3, "encoder_embedding_dim": 512, "n_frames_per_step": 1, "decoder_rnn_dim": 1024, "prenet_dim": 256, "max_decoder_steps": 2000, "gate_threshold": 0.5, "p_attention_dropout": 0.1, "p_decoder_dropout": 0.1, "decoder_no_early_stopping": false, "attention_rnn_dim": 1024, "attention_dim": 128, "attention_location_n_filters": 32, "attention_location_kernel_size": 31, "postnet_embedding_dim": 512, "postnet_kernel_size": 5, "postnet_n_convolutions": 5}
:::NVLOGv0.2.2 Tacotron2_PyT 1566787699.639706850 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) run_start
:::NVLOGv0.2.2 Tacotron2_PyT 1566787704.252790451 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) train_loop
:::NVLOGv0.2.2 Tacotron2_PyT 1566787704.253896713 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) train_epoch_start: 0
Batch: 0/3125 epoch 0
:::NVLOGv0.2.2 Tacotron2_PyT 1566787704.416965008 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) train_iter_start: 0
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
/pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype 

ends with: 

Traceback (most recent call last):
  File "train.py", line 513, in <module>
    main()
  File "train.py", line 433, in main
    raise Exception("loss is NaN")
Exception: loss is NaN

![Screenshot from 2019-08-25 21-50-18](https://user-images.githubusercontent.com/3030588/63661992-5c510400-c782-11e9-8c0c-2a831588ac64.png)

**Comment by wizardk** [comment]
> Running torch 1.2.0
> 
> Anyone else get this error?
> 
> $python3 train.py -m Tacotron2 --epochs 100 -lr 0.05 -bs 16 --output_directory=/home/merlin/opfoghorn/tacotron2/outputdir/ --log-file=nvlog.json
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787699.469461679 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:279) run_start
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787699.482044220 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) cpu_info: {"num": 48, "name": "AMD Ryzen Threadripper 2970WX 24-Core Processor"}
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787699.491433620 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) mem_info: {"ram": "62G"}
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787699.636062145 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) gpu_info: {"driver_version": "430.40", "num": 2, "name": ["Quadro M4000", "GeForce GTX 1050 Ti"], "mem": ["8126 MiB", "4032 MiB"]}
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787699.639187098 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) args: {"output_directory": "/home/merlin/opfoghorn/tacotron2/outputdir/", "dataset_path": "./", "model_name": "Tacotron2", "log_file": "nvlog.json", "phrase_path": null, "waveglow_checkpoint": null, "tacotron2_checkpoint": null, "anneal_steps": null, "anneal_factor": 0.1, "epochs": 100, "epochs_per_checkpoint": 50, "seed": 1234, "dynamic_loss_scaling": true, "amp_run": false, "cudnn_enabled": false, "cudnn_benchmark": false, "disable_uniform_initialize_bn_weight": false, "use_saved_learning_rate": false, "learning_rate": 0.05, "weight_decay": 1e-06, "grad_clip_thresh": 1.0, "batch_size": 4, "grad_clip": 5.0, "load_mel_from_disk": false, "training_files": "filelists/ljs_audio_text_train_filelist.txt", "validation_files": "filelists/ljs_audio_text_val_filelist.txt", "text_cleaners": ["english_cleaners"], "max_wav_value": 32768.0, "sampling_rate": 22050, "filter_length": 1024, "hop_length": 256, "win_length": 1024, "mel_fmin": 0.0, "mel_fmax": 8000.0, "rank": 0, "world_size": 1, "dist_url": "tcp://localhost:23456", "group_name": "group_name", "dist_backend": "nccl", "mask_padding": false, "n_mel_channels": 80, "n_symbols": 148, "symbols_embedding_dim": 512, "encoder_kernel_size": 5, "encoder_n_convolutions": 3, "encoder_embedding_dim": 512, "n_frames_per_step": 1, "decoder_rnn_dim": 1024, "prenet_dim": 256, "max_decoder_steps": 2000, "gate_threshold": 0.5, "p_attention_dropout": 0.1, "p_decoder_dropout": 0.1, "decoder_no_early_stopping": false, "attention_rnn_dim": 1024, "attention_dim": 128, "attention_location_n_filters": 32, "attention_location_kernel_size": 31, "postnet_embedding_dim": 512, "postnet_kernel_size": 5, "postnet_n_convolutions": 5}
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787699.639706850 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) run_start
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787704.252790451 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) train_loop
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787704.253896713 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) train_epoch_start: 0
> Batch: 0/3125 epoch 0
> :::NVLOGv0.2.2 Tacotron2_PyT 1566787704.416965008 (/home/merlin/gits/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/dllogger/logger.py:251) train_iter_start: 0
> /pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.
> /pytorch/aten/src/ATen/native/cuda/LegacyDefinitions.cpp:14: UserWarning: masked_fill_ received a mask with dtype
> 
> ends with:
> 
> Traceback (most recent call last):
> File "train.py", line 513, in 
> main()
> File "train.py", line 433, in main
> raise Exception("loss is NaN")
> Exception: loss is NaN
> 
> ![Screenshot from 2019-08-25 21-50-18](https://user-images.githubusercontent.com/3030588/63661992-5c510400-c782-11e9-8c0c-2a831588ac64.png)

using pytorch 1.1.0

**Comment by idcore** [comment]
Had the same issue, attention layer tensor filled with Nans on 2nd pass resultin in Nan loss. Downgrading to torch 1.1.0 resolved issue.

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
