### ISSUE TITLE
HParams was removed from tensorflow 2.0

### ISSUE THREAD

**Issue by sih4sing5hong5** [NVIDIA/tacotron2#278]
There is `tf.contrib.training.HParams` in `hparams.py`
```
+ python train.py --output_directory=/data/ --log_directory=log
Traceback (most recent call last):
  File "train.py", line 278, in <module>
    hparams = create_hparams(args.hparams)
  File "/workspace/tacotron2/hparams.py", line 8, in create_hparams
    hparams = tf.contrib.training.HParams(
AttributeError: module 'tensorflow' has no attribute 'contrib'
[ERROR] failed to execute task "tacotron2:": exited with non-zero status code 1
```

Related issue:
- https://github.com/tensorflow/community/issues/148
- https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/hparams/api.py

**Comment by Geekgineer** [comment]
Quick and dirty install 'tensorflow' which has attribute 'contrib'
use "$ conda remove" & "$ conda install" if you have conda env
```py
pip uninstall  tensorflow
pip uninstall  tensorflow-gpu
pip install tensorflow==1.12.0
```
> Note that tf 1.12.0 comes with GPU support also watch for you CUDA version

**Comment by v-nhandt21** [comment]
![image](https://user-images.githubusercontent.com/36092323/138568927-f2be1ac8-a602-4b85-bddc-d1b6b510c1bc.png)
For who get the this error in the future, tensorflow > 2.x not support contrib, just replace it by dict

**Comment by srothhh** [comment]
@v-nhandt21 Hello. I tried with your solution. Unfortunately, while loading model, there is an AttributionError: module 'AttrDict' has no attribute 'mask_padding'. Do this occurred to you? Thanks.
<img width="1093" alt="Screen Shot 2565-01-05 at 15 35 10" src="https://user-images.githubusercontent.com/71324265/148186336-f6d8ac3d-43b2-458e-8fdf-9756d65a3253.png">

**Comment by CrackerHax** [comment]
> ![image](https://user-images.githubusercontent.com/36092323/138568927-f2be1ac8-a602-4b85-bddc-d1b6b510c1bc.png) For who get the this error in the future, tensorflow > 2.x not support contrib, just replace it by dict

What a lazy answer

**Comment by v-nhandt21** [comment]
```
class AttrDict(dict):
    def __init__(self, *args, **kwargs):
        super(AttrDict, self).__init__(*args, **kwargs)
        self.__dict__ = self


def create_hparams(hparams_string=None, verbose=False):
    """Create model hyperparameters. Parse nondefault from given string."""

    hparams = AttrDict({
        ################################
        # Experiment Parameters        #
        ################################
        "epochs":1500,
        "iters_per_checkpoint":1000,
        "seed":1234,
        "dynamic_loss_scaling":True,
        "fp16_run":False,
        "distributed_run":False,
        "dist_backend":"nccl",
        "dist_url":"tcp://localhost:14897",
        "cudnn_enabled":True,
        "cudnn_benchmark":False,
        "ignore_layers":['embedding.weight'],
        # freeze_layers":['encoder'], # Freeze tacotron2 layer for finetuning

        ################################
        # Data Parameters             #
        ################################
        "load_mel_from_disk":False,
        "load_phone_from_disk":True,

        "training_files":'',
        "validation_files":'',

        "text_cleaners":['english_cleaners'],

        ################################
        # Audio Parameters             #
        ################################
        "max_wav_value":32768.0,
        "sampling_rate":22050,
        "filter_length":1024,
        "hop_length":256,
        "win_length":1024,
        "n_mel_channels":80,
        "mel_fmin":0.0,
        "mel_fmax":8000.0,

        ################################
        # Model Parameters             #
        ################################
        "n_symbols": 313,
        "symbols_embedding_dim":512,
        "alignloss": "L2",
        "attention": "StepwiseMonotonicAttention",

        # Encoder parameters
        "encoder_kernel_size":5,
        "encoder_n_convolutions":3,
        "encoder_embedding_dim":512,

        # Decoder parameters
        "n_frames_per_step":1,  # currently only 1 is supported
        "decoder_rnn_dim":1024,
        "prenet_dim":256,
        "max_decoder_steps":1000,
        "gate_threshold":0.001,
        "p_attention_dropout":0.1,
        "p_decoder_dropout":0.1,

        # Attention parameters
        "attention_rnn_dim":1024,
        "attention_dim":128,

        # Location Layer parameters
        "attention_location_n_filters":32,
        "attention_location_kernel_size":31,

        # Mel-post processing network parameters
        "postnet_embedding_dim":512,
        "postnet_kernel_size":5,
        "postnet_n_convolutions":5,

        ################################
        # Optimization Hyperparameters #
        ################################
        "use_saved_learning_rate":True,
        "learning_rate":1e-3,
        "weight_decay":1e-6,
        "grad_clip_thresh":1.0,
        "batch_size":32, # each gpus
        "mask_padding":True  # set model's padded outputs to padded values
    })

    if hparams_string:
        hps = hparams_string[1:-2].split("-")
        for hp in hps:
            k,v = hp.split(":")
            if k in hparams:
                hparams[k] = v
                print("Set hparam: " + k + " to " + v)

    return hparams
```

In train script, use it as follow

```
parser.add_argument('--hparams', type=str)
hparams = create_hparams(args.hparams)
```

@CrackerHax haha, I just improve my laziness

@srothhh you just add this param for your code: mask_padding

**Comment by yadagiri31** [comment]
i am facing parser not found error

**Comment by murugan001ab** [comment]
NameError                                 Traceback (most recent call last)

[<ipython-input-37-0fd19e1e7060>](https://localhost:8080/#) in <cell line: 1>()
----> 1 parser.add_argument('--hparams', type=str)
      2 hparams = create_hparams(args.hparams)

NameError: name 'parser' is not defined
