### ISSUE TITLE
Way to inference using cpu?

### ISSUE THREAD

**Issue by kumakichiy** [NVIDIA/tacotron2#310]
Hi there,
I am trying to compare the performance of CPU and GPU in Jetson Xavier with tacotron.
TacoTron2 works fine in GPU. 

Below is my code and log, and the modification for cpu.
Please kindly help, thank you in advance .

log is like:
`Tacotron2 load 7.466493844985962
<class 'glow.WaveGlow'>
Traceback (most recent call last):
  File "./server.py", line 62, in <module>
    denoiser = Denoiser(waveglow)
  File "waveglow/denoiser.py", line 30, in __init__
    bias_audio = waveglow.infer(mel_input, sigma=0.0).float()
  File "waveglow/glow.py", line 276, in infer
    output = self.WN[k]((audio_0, spect))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "waveglow/glow.py", line 155, in forward
    audio = self.start(audio)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 187, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

`import warnings
warnings.simplefilter('ignore', Warning)
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import matplotlib
matplotlib.use("Agg")
import matplotlib.pylab as plt
import sys
sys.path.append('waveglow/')
import numpy as np
import torch
import pyaudio
import gc
import time
import socket

from hparams import create_hparams
from model import Tacotron2
from layers import TacotronSTFT, STFT
from audio_processing import griffin_lim
from train import load_model
from text import text_to_sequence
from denoiser import Denoiser

import signal
import sys
def signal_handler(signal,frame):
    print('Exiting')
    sys.exit(0)

def plot_data(data, figsize=(16, 4)):
    fig, axes = plt.subplots(1, len(data), figsize=figsize)
    for i in range(len(data)):
        axes[i].imshow(data[i], aspect='auto', origin='bottom',
                       interpolation='none')

print('Start server.py')
# Initialize tacotron2
torch.cuda.synchronize()
time0 = time.time()

hparams = create_hparams()
hparams.sampling_rate = 22050

checkpoint_path = "../tacotron2-model/tacotron2_statedict.pt"
model = load_model(hparams)
-model.load_state_dict(torch.load(checkpoint_path)['state_dict'])
+model.load_state_dict(torch.load(checkpoint_path,map_location='cpu')['state_dict'])
_ = model.cuda().eval().half()

torch.cuda.synchronize()
time1 = time.time()
print('Tacotron2 load',time1 - time0)

# Initialize waveglow
waveglow_path = '../tacotron2-model/waveglow_256channels_ljs_v3.pt'

**change from**
waveglow = torch.load(waveglow_path)['model']
waveglow.cuda().eval().half()
**to**
**waveglow = torch.load(waveglow_path,map_location='cpu')['model']
waveglow.eval()**

for k in waveglow.convinv:
    k.float()
denoiser = Denoiser(waveglow)

torch.cuda.synchronize()
time2 = time.time()
print('waveglow init ',time2 - time1)

# Open stream
p = pyaudio.PyAudio()
stream = p.open(format = pyaudio.paFloat32,
                channels = 1,
                #rate = 44100,
                rate = 48000,
                output = True,
                output_device_index=24,
                frames_per_buffer = 1024)
time3 = time.time()
print('open audio stream ', time3 - time2)

# Recieve messages
print('wait messages')
loop_end = False
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind(('TacoTron', 50007))
    s.listen(1)
    while True:
        conn, addr = s.accept()
        signal.signal(signal.SIGINT,signal_handler)
        with conn:
            while True:
                data = conn.recv(1024)
                if not data:
                    break
                print('data : {}, addr: {}'.format(data, addr))

                # When received ".", this program will end.
                if data.decode('utf-8')[0] == ".":
                    print("End")
                    conn.sendall(b'End')
                    loop_end = True
                    break

                # Inference by tacotron2
                torch.cuda.synchronize()
                time4 = time.time()
                sequence = np.array(text_to_sequence(data.decode('utf-8'), ['english_cleaners']))[None, :]
 
**change from**
               sequence = torch.autograd.Variable(torch.from_numpy(sequence)).cuda().long()
**to**
                **sequence = torch.autograd.Variable(torch.from_numpy(sequence)).cpu().long()**
                mel_outputs, mel_outputs_postnet, _, alignments = model.inference(sequence)
                torch.cuda.synchronize()
                time5 = time.time()
                print('Tacotron2 infer ',time5 - time4)

                # Inference by waveglow
                with torch.no_grad():
                    audio = waveglow.infer(mel_outputs_postnet, sigma=0.666)
                    torch.cuda.synchronize()
                time6 = time.time()
                print('waveglow infer ',time6 - time5)
                np.save('audio',audio[0].data.cpu().numpy())
                list_audio = []
                for i in audio[0].data.cpu().numpy():
                    list_audio.append(i)
                    list_audio.append(i)
                audio1_2 = np.array(list_audio)

                # Output to speaker
                print("play")
                stream.write(audio1_2.astype(np.float32).tostring())

                # Return to client
                conn.sendall(b'Received: ' + data)

        if loop_end == True:
            break

stream.close()
p.terminate()`

**Comment by kumakichiy** [comment]
Followed a nice people's solution to shift gpu inference to cpu.
Working perfertly.
Close issue.
https://github.com/syoyo/FastSpeech/commit/5e218913a7eacc2ea3eae985add7758208f03f39
