### ISSUE TITLE
Dockerfile Missing Apex

### ISSUE THREAD

**Issue by ColeMurray** [NVIDIA/tacotron2#332]
Hello Nvidia,

Following the instructions, the README suggests downloading the apex repo, prior to building the Dockefile.

Is there a reason to not include the apex directory in the dockerfile? 
e.g. ```RUN git clone https://github.com/NVIDIA/apex```

**Comment by pneumoman** [comment]
yeah I think that might be the least of your troubles -  The code is for python 2 and all the container images are python 3

**Comment by pneumoman** [comment]
If you check out my fork of mellotron there's a passable Docker file.  Hack at will

**Comment by TotzkePaul** [comment]
Where is the docker file?

**Comment by pneumoman** [comment]
[Dockerfile](https://github.com/pneumoman/mellotron/blob/Docker/docker/Dockerfile)
you might want to take a look at the included scripts, for firing it off.

**Comment by TotzkePaul** [comment]
Thanks, I didn't see the docker branch. Is your docker branch of mellotron in a working state? I've been researching every flavor of TacoTron I could find but I everything seems very out of date. 

Mellotron seems like its what I really want to be using. 

Anyways for this repo, I'm trying to dev on my Docker on Windows but now I get "Warning: Torch did not find available GPUs on this system." and adding `--runtime=nvidia` doesn't help. Not sure if its my CUDA 10.2 or if it really doesn't work for nvidia docker.

I just want one of these tacotrons to work in Docker

```
FROM pytorch/pytorch:nightly-devel-cuda10.0-cudnn7
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}

RUN apt-get update -y

RUN pip install numpy scipy matplotlib librosa==0.6.0 tensorflow tensorboardX inflect==0.2.5 Unidecode==1.0.22 pillow jupyter

WORKDIR /
RUN git clone https://github.com/NVIDIA/apex

#ADD apex /apex/
WORKDIR /apex/
RUN pip install -v --no-cache-dir --global-option="--pyprof" --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

**Comment by pneumoman** [comment]
I have not actually tested this with Tacotron but I have to believe it should work - mellotron is mostly based on tacotron.  With regards to your GPU error, do you have other containers that are working?  I might suggest going out to [nvidia/ngc](https://ngc.nvidia.com/ ) to get one of their canned examples.  I think this code likes relatively modern GPUs,  I've tried to run things off of some not what I would call ancient but not new laptops, and they did not support the required API.  If that's the case the only solution is to update the hardware.  Since this is containerized, the Cuda,  Cudnn, and Apex are in the container, you just need a proper driver.  I haven't used this container with windows, or windows docker for that matter, so I can't help you with that.  note: if you find that TensorFlow is causing your GPU issue, it's not really used - they only use TF to wrangle the hyperparams.

**Comment by TotzkePaul** [comment]
I switched to Ubuntu 16.04. and I can see my GPUs now. (sudo docker run --gpus all nvidia/cuda:9.0-base nvidia-smi) I don't think its possible to do docker on windows with cuda.

Mellotron: Weird docker issue was downloading every container 3 times. 


Rayhane-mamah's Tacotron: I got a docker image to start preprocessing

Nvidia's Tacotron2: I have 10.2 cuda installed but I think most containers aren't compatible with it

Rayhane-mamah/Tacotron-2
```
FROM continuumio/anaconda3:latest
FROM tensorflow/tensorflow:1.11.0-gpu-py3

RUN apt-get update
RUN apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg wget git vim

COPY ./ /tacotron2/

RUN pip install --upgrade pip
RUN ls
RUN pwd
WORKDIR /tacotron2
RUN pip install -r requirements.txt
```

Requirements.txt
```
falcon==1.2.0
inflect==0.2.5
audioread==2.1.5
librosa==0.6.3
matplotlib==2.0.2
numpy==1.14.6
scipy==1.0.0
llvmlite==0.31.0
tqdm==4.11.2
Unidecode==0.4.20
pyaudio==0.2.11
sounddevice==0.3.10
lws
keras==2.1.6
```

Rayhane-mamah's Tacotron output forr preprocessing:
```
root@147e6ad52570:/tacotron2# TMPDIR=$HOME/tmp
root@147e6ad52570:/tacotron2# python preprocess.py --dataset='M-AILABS' --language='en_US' --voice='female' --reader='mary_ann' --merge_books=True --base_dir='./datasets/M-AILABS'
initializing preprocessing..
Selecting data folders..
 10%|######7                                                            | 1356/13371 [01:42<20:36,  9.71it/s]file ./datasets/M-AILABS/en_US/by_book/female/mary_ann/midnight_passenger/wavs/midnight_passenger_05_f000269.wav present in csv metadata is not present in wav folder. skipping!
 29%|###################1                                               | 3831/13371 [04:49<16:25,  9.68it/s]concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/tacotron2/datasets/preprocessor.py", line 159, in _process_utterance
    np.save(os.path.join(linear_dir, linear_filename), linear_spectrogram.T, allow_pickle=False)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 511, in save
    pickle_kwargs=pickle_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/format.py", line 597, in write_array
    array.tofile(fp)
OSError: 681625 requested and 65504 written
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "preprocess.py", line 112, in <module>
    main()
  File "preprocess.py", line 108, in main
    run_preprocess(args, modified_hp)
  File "preprocess.py", line 83, in run_preprocess
    preprocess(args, input_folders, output_folder, hparams)
  File "preprocess.py", line 17, in preprocess
    metadata = preprocessor.build_from_path(hparams, input_folders, mel_dir, linear_dir, wav_dir, args.n_jobs, tqdm=tqdm)
  File "/tacotron2/datasets/preprocessor.py", line 42, in build_from_path
    return [future.result() for future in tqdm(futures) if future.result() is not None]
  File "/tacotron2/datasets/preprocessor.py", line 42, in <listcomp>
    return [future.result() for future in tqdm(futures) if future.result() is not None]
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
OSError: 681625 requested and 65504 written
```

**Comment by TotzkePaul** [comment]
`conda install -c conda-forge nvidia-apex`
