### ISSUE TITLE
Training data question: shape [x, x, x] is invalid for input of size Y

### ISSUE THREAD

**Issue by scripples** [NVIDIA/tacotron2#362]
I think I'm having a problem with my custom dataset, and I'm not sure how to solve the issue. I've passed a normal test and validation .txt to the hparams, which point to my directory containing the (selfmade) WAV files.  I tried to make sure the WAVs were 16-bit PCM and stripped them of metadata, just to be sure. I'd be able to fit it in other contexts, but I haven't worked with audio data in this context before, so I'm a bit lost on why my audio data is causing a shape error. 

If anyone has any advice, I'd be really grateful. Here's the traceback:

Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/notebooks/tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/notebooks/tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/notebooks/tacotron2/data_utils.py", line 46, in get_mel
    melspec = self.stft.mel_spectrogram(audio_norm)
  File "/notebooks/tacotron2/layers.py", line 76, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "/notebooks/tacotron2/stft.py", line 84, in transform
    input_data = input_data.view(num_batches, 1, num_samples)
RuntimeError: shape '[1, 1, 212628]' is invalid for input of size 425256

And a sample of my training data list for good measure:
saltz/clips/saltz_0830.wav|Most galleries, curators, collectors, and critics learn about artists through other artists.
saltz/clips/saltz_0985.wav|This means your work is alive, that it has more than just you in it.
saltz/clips/saltz_0132.wav|Start thinking about creating.

Thanks for the help!

**Comment by CookiePPP** [comment]
@scripples 
They might be stereo files instead of mono

**Comment by scripples** [comment]
That was it! Thanks for the help!
