### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by WellImDumb** [NVIDIA/tacotron2#423]
(py2) C:\Users\misho\tacotron2>python train.py --output_directory=outdir --log_directory=logdir
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 208, in train
    for i, batch in enumerate(train_loader):
  File "C:\Users\misho\Anaconda3\envs\py2\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\misho\Anaconda3\envs\py2\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\misho\Anaconda3\envs\py2\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\Users\misho\Anaconda3\envs\py2\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\misho\Anaconda3\envs\py2\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\misho\Anaconda3\envs\py2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\misho\Anaconda3\envs\py2\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\misho\tacotron2\data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "C:\Users\misho\tacotron2\data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "C:\Users\misho\tacotron2\data_utils.py", line 42, in get_mel
    sampling_rate, self.stft.sampling_rate))
IndexError: tuple index out of range

**Comment by SakuBorder** [comment]
Have you solved this problem?I also disturbed by this problem.

**Comment by Ayush-Rawal** [comment]
This is a sampling rate issue. Either change the sampling rate in hparams to match the sampling rate of your audio, or downsample/upsample your audio to LJ Speech's sampling rate (22050). I recommend the later as it will give you better waveglow performance

**Comment by SakuBorder** [comment]
Thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVIDIA/tacotron2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月7日(星期一) 下午3:47
收件人:&nbsp;"NVIDIA/tacotron2"<tacotron2@noreply.github.com&gt;;
抄送:&nbsp;"Begin"<1476255048@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [NVIDIA/tacotron2] IndexError: tuple index out of range (#423)





 
This is a sampling rate issue. Either change the sampling rate in hparams to match the sampling rate of your audio, or downsample/upsample your audio to LJ Speech's sampling rate (22050). I recommend the later as it will give you better waveglow performance
