### ISSUE TITLE
RuntimeError: code is too big 

### ISSUE THREAD

**Issue by BasmaOUKIT** [NVIDIA/tacotron2#437]
I can't lunch Tacotron2 training
`FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
Warm starting model from checkpoint 'tacotron2_statedict.pt'
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 208, in train
    for i, batch in enumerate(train_loader):
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubuntu/tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/home/ubuntu/tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/home/ubuntu/tacotron2/data_utils.py", line 46, in get_mel
    melspec = self.stft.mel_spectrogram(audio_norm)
  File "/home/ubuntu/tacotron2/layers.py", line 76, in mel_spectrogram
    magnitudes, phases = self.stft_fn.transform(y)
  File "/home/ubuntu/tacotron2/stft.py", line 95, in transform
    padding=0)
RuntimeError: code is too big
`
I use an EC2 instance with Tesla T4 cuda 10.0 
Pytorch==1.1.0 , torchvision==0.3.0 and  numpy==1.16.0 , I have lunched many other training with the same configuration and I don't understand why it's breaking now.
I tried the solutions given here  #125 still having the same error.
If I have to change Pytorch version, which one should I use and what are other libraries versions that are compatible with it.
Thank you.

**Comment by BasmaOUKIT** [comment]
@rafaelvalle Do you have any solution? Is it because of Requirements.txt versions?

**Comment by 1090167369** [comment]
Hello, blogger, can you tell me that your problem has been solved? Can you tell me your solution.

**Comment by 1090167369** [comment]
I'm crazy about this problem
