### ISSUE TITLE
'Parameter' object has no attribute '_execution_engine' when running with multi-GPUs

### ISSUE THREAD

**Issue by MlWoo** [NVIDIA/tacotron2#44]
An error happened when the repo runned on 2-gpus of single node with the commandline:
```bash
CUDA_VISIBLE_DEVICES=2,3 python -m multiproc train.py --n_gpus=2 --rank=0 --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True
```
The import info echoed at the begining is below: 
```
['train.py', '--n_gpus=2', '--rank=0', '--output_directory=outdir', '--log_directory=logdir', '--hparams=distributed_run=True,fp16_run=True', '--n_gpus=2', '--group_name=group_2018_06_19-083304', '--rank=0']
['train.py', '--n_gpus=2', '--rank=0', '--output_directory=outdir', '--log_directory=logdir', '--hparams=distributed_run=True,fp16_run=True', '--n_gpus=2', '--group_name=group_2018_06_19-083304', '--rank=1']
FP16 Run: True
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing distributed
Done initializing distributed
```
Then an error occured:
```
Traceback (most recent call last):
  File "train.py", line 291, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 222, in train
    optimizer.backward(loss)
  File "/home/mlwoo/repo/tacotron2/fp16_optimizer.py", line 362, in backward
    self.loss_scaler.backward(loss.float())
  File "/home/mlwoo/repo/tacotron2/loss_scaler.py", line 80, in backward
    scaled_loss.backward()
  File "/home/mlwoo/dev-bin/anaconda3/envs/wavenet/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/mlwoo/dev-bin/anaconda3/envs/wavenet/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/mlwoo/repo/tacotron2/distributed.py", line 95, in allreduce_hook
    param._execution_engine.queue_callback(allreduce_params)
AttributeError: 'Parameter' object has no attribute '_execution_engine'
```
And the significant dpt file was also not generated in the folder although the info showed the initialization was Done.

I also tried to run the repo with the commandline:
```bash
CUDA_VISIBLE_DEVICES=2,3 python train.py --n_gpus=2 --rank=0 --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True
```
Then it hung at the initialization like what the issue #38 metioned. The content of dpt file is different from that of issue #38 :
```
group_name# 0 32861 6 10.128.2.14 172.17.0.1 10.128.1.14 fe80::ae1f:6bff:fe27:b358 fe80::526b:4bff:fe2f:21c8 fe80::1363:7bed:662d:ea3e
```
Could you help me to step out the dilema?

**Comment by rafaelvalle** [comment]
Probably there's a solution here: https://github.com/NVIDIA/tacotron2/issues/32

**Comment by MlWoo** [comment]
@rafaelvalle Yeah, I did resovle the problem with that solution actually.
