### ISSUE TITLE
List Index Out Of Range

### ISSUE THREAD

**Issue by Ben10lightningx** [NVIDIA/tacotron2#528]
When I try to run the command "python train.py -c config.json -p train_config.output_directory=outdir data_config.use_attn_prior=1" I get this

train_config.output_directory=outdir
train_config.output_directory:outdir was not parsed
output_directory=outdir
output_directory:outdir was not parsed
data_config.use_attn_prior=1
use_attn_prior=1
{'train_config': {'output_directory': 'outdir', 'epochs': 10000000, 'optim_algo': 'RAdam', 'learning_rate': 0.001, 'weight_decay': 1e-06, 'grad_clip_val': 1, 'sigma': 1.0, 'iters_per_checkpoint': 1000, 'batch_size': 6, 'seed': 1234, 'c
heckpoint_path': '', 'ignore_layers': [], 'finetune_layers': [], 'include_layers': ['speaker', 'encoder', 'embedding'], 'warmstart_checkpoint_path': '', 'with_tensorboard': True, 'fp16_run': True, 'gate_loss': True, 'use_ctc_loss': Tru
e, 'ctc_loss_weight': 0.01, 'blank_logprob': -8, 'ctc_loss_start_iter': 10000}, 'data_config': {'training_files': 'C:\\Scripts\\FridayVoice\\flowtron\\filelists\\list.txt', 'validation_files': 'C:\\Scripts\\FridayVoice\\flowtron\\filel
ists\\list.txt', 'text_cleaners': ['flowtron_cleaners'], 'p_arpabet': 0.5, 'cmudict_path': 'data/cmudict_dictionary', 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'mel_fmin': 0.0, 'mel_fmax': 80
00.0, 'max_wav_value': 32768.0, 'use_attn_prior': 1, 'attn_prior_threshold': 0.0, 'prior_cache_path': '/attention_prior_cache', 'betab_scaling_factor': 1.0, 'keep_ambiguous': False}, 'dist_config': {'dist_backend': 'nccl', 'dist_url':
'tcp://localhost:54321'}, 'model_config': {'n_speakers': 1, 'n_speaker_dim': 128, 'n_text': 185, 'n_text_dim': 512, 'n_flows': 2, 'n_mel_channels': 80, 'n_attn_channels': 640, 'n_hidden': 1024, 'n_lstm_layers': 2, 'mel_encoder_n_hidden
': 512, 'n_components': 0, 'mean_scale': 0.0, 'fixed_gaussian': True, 'dummy_speaker_embedding': False, 'use_gate_layer': True, 'use_cumm_attention': False}}
> got rank 0 and world size 1 ...
Initializing RAdam optimizer
Flowtron(
  (speaker_embedding): Embedding(1, 128)
  (embedding): Embedding(185, 512)
  (flows): ModuleList(
    (0): AR_Step(
      (conv): Conv1d(1024, 160, kernel_size=(1,), stride=(1,))
      (lstm): LSTM(1664, 1024, num_layers=2)
      (attention_lstm): LSTM(80, 1024)
      (attention_layer): Attention(
        (softmax): Softmax(dim=2)
        (query): LinearNorm(
          (linear_layer): Linear(in_features=1024, out_features=640, bias=False)
        )
        (key): LinearNorm(
          (linear_layer): Linear(in_features=640, out_features=640, bias=False)
        )
        (value): LinearNorm(
          (linear_layer): Linear(in_features=640, out_features=640, bias=False)
        )
        (v): LinearNorm(
          (linear_layer): Linear(in_features=640, out_features=1, bias=False)
        )
      )
      (dense_layer): DenseLayer(
        (layers): ModuleList(
          (0): LinearNorm(
            (linear_layer): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (1): LinearNorm(
            (linear_layer): Linear(in_features=1024, out_features=1024, bias=True)
          )
        )
      )
    )
    (1): AR_Back_Step(
      (ar_step): AR_Step(
        (conv): Conv1d(1024, 160, kernel_size=(1,), stride=(1,))
        (lstm): LSTM(1664, 1024, num_layers=2)
        (attention_lstm): LSTM(80, 1024)
        (attention_layer): Attention(
          (softmax): Softmax(dim=2)
          (query): LinearNorm(
            (linear_layer): Linear(in_features=1024, out_features=640, bias=False)
          )
          (key): LinearNorm(
            (linear_layer): Linear(in_features=640, out_features=640, bias=False)
          )
          (value): LinearNorm(
            (linear_layer): Linear(in_features=640, out_features=640, bias=False)
          )
          (v): LinearNorm(
            (linear_layer): Linear(in_features=640, out_features=1, bias=False)
          )
        )
        (dense_layer): DenseLayer(
          (layers): ModuleList(
            (0): LinearNorm(
              (linear_layer): Linear(in_features=1024, out_features=1024, bias=True)
            )
            (1): LinearNorm(
              (linear_layer): Linear(in_features=1024, out_features=1024, bias=True)
            )
          )
        )
        (gate_layer): LinearNorm(
          (linear_layer): Linear(in_features=1664, out_features=1, bias=True)
        )
      )
    )
  )
  (encoder): Encoder(
    (convolutions): ModuleList(
      (0): Sequential(
        (0): ConvNorm(
          (conv): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,))
        )
        (1): InstanceNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
      )
      (1): Sequential(
        (0): ConvNorm(
          (conv): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,))
        )
        (1): InstanceNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
      )
      (2): Sequential(
        (0): ConvNorm(
          (conv): Conv1d(512, 512, kernel_size=(5,), stride=(1,), padding=(2,))
        )
        (1): InstanceNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
      )
    )
    (lstm): LSTM(512, 256, batch_first=True, bidirectional=True)
  )
)
Traceback (most recent call last):
  File "C:\Scripts\FridayVoice\flowtron\train.py", line 415, in <module>
    train(n_gpus, rank, **train_config)
  File "C:\Scripts\FridayVoice\flowtron\train.py", line 256, in train
    train_loader, valset, collate_fn = prepare_dataloaders(
  File "C:\Scripts\FridayVoice\flowtron\train.py", line 63, in prepare_dataloaders
    trainset = Data(data_config['training_files'],
  File "C:\Scripts\FridayVoice\flowtron\data.py", line 74, in __init__
    self.speaker_ids = self.create_speaker_lookup_table(
  File "C:\Scripts\FridayVoice\flowtron\data.py", line 144, in create_speaker_lookup_table
    speaker_ids = np.sort(np.unique([x[2] for x in audiopaths_and_text]))
  File "C:\Scripts\FridayVoice\flowtron\data.py", line 144, in <listcomp>
    speaker_ids = np.sort(np.unique([x[2] for x in audiopaths_and_text]))
IndexError: list index out of range

**Comment by Ben10lightningx** [comment]
Turns out there was a mistake in one of the transcripts of my audio files, works now
