### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'DUMMY/LJ009-0042.wav'

### ISSUE THREAD

**Issue by Aliraheem** [NVIDIA/tacotron2#530]
Hello everyone, I am trying to run Tacotron2. I am having this error below: 
Any suggestion, please?

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 290, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 208, in train
    for i, batch in enumerate(train_loader):
  File "/home/ali/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ali/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/ali/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/ali/.local/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ali/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ali/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ali/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ali/tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/home/ali/tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/home/ali/tacotron2/data_utils.py", line 39, in get_mel
    audio, sampling_rate = load_wav_to_torch(filename)
  File "/home/ali/tacotron2/utils.py", line 14, in load_wav_to_torch
    sampling_rate, data = read(full_path)
  File "/home/ali/.local/lib/python3.6/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'DUMMY/LJ009-0042.wav'

**Comment by CookiePPP** [comment]
https://github.com/NVIDIA/tacotron2#setup

step 5 of setup.
Replace `DUMMY` with the path to your LJSpeech dataset audio folder.

**Comment by DivyanshRathi** [comment]
I am facing the same problem, and I have implemented step 5 of setup, instead of "DUMMY" in the last line, it says the following.
No such file or directory: 'ljs_dataset_folder/wavs/LJ009-0042.wav'

I checked all the files and didn't find this file either.

**Comment by urmikakasi** [comment]
Did you find a solution to this? I'm having the same issue too.

**Comment by Aliraheem** [comment]
The directories of waves in train and validation files (tacotron2/filelists/) should be the same as your dataset path. 
Use this command to update them: 
Update .wav paths: sed -i -- 's,DUMMY,ljs_dataset_folder/wavs,g' filelists/*.txt

**Comment by postovalov** [comment]
For example, for colab users, if you are loading the LJSpeech dataset into "content" folder and unzipped it in the same location, use this command with absolute path:

sed -i -- 's,/content/LJSpeech-1.1./wavs,ljs_dataset_folder/wavs,g' filelists/*.txt

**Comment by a897456** [comment]
I copy the files from LJSpeech-1.1 into the DUMMY folder
