### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib'

### ISSUE THREAD

**Issue by Colabnoob** [NVIDIA/tacotron2#558]
I'm a noob to tacotron2 and i'm running on a cpu so maybe that's why i'm getting these errors. can someone help me solve this? i installed different versions of tensorflow, look online for hours and can't resolve my issue.

python train.py --output_directory=outdir --log_directory=logdir
C:\Users\darre\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\darre\anaconda3\lib\site-packages\numpy\.libs\libopenblas.4SP5SUA7CBGXUEOC35YP2ASOICYYEQZZ.gfortran-win_amd64.dll
C:\Users\darre\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Traceback (most recent call last):
  File "C:\Users\darre\OneDrive\Desktop\tacotron2\train.py", line 278, in <module>
    hparams = create_hparams(args.hparams)
  File "C:\Users\darre\OneDrive\Desktop\tacotron2\hparams.py", line 8, in create_hparams
    hparams = tf.contrib.training.HParams(
AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by postovalov** [comment]
tf.contrib has moved out of TF starting TF 2.0 alpha.
You have to use TF1 instead on TF2. If you're colab user, then just past it on the top and run.

%tensorflow_version 1.x

OR

Take a look at these tf 2.0 release notes https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0-alpha0
You can upgrade your TF 1.x code to TF 2.x using the tf_upgrade_v2 script https://www.tensorflow.org/alpha/guide/upgrade

**Comment by lisabecker** [comment]
This seems to be a common problem with Tacotron2: #366

**Comment by ruapotato** [comment]
My Debain 11 box seems to be unable to install tf 1.x. Is there a workaround to get this working with 2.x without needed to use a colab project? 
```
# sudo pip3 install tensorflow==1.15.5
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.5 (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0)
ERROR: No matching distribution found for tensorflow==1.15.5
# python --version
Python 3.9.2
```

**Comment by postovalov** [comment]
> My Debain 11 box seems to be unable to install tf 1.x. Is there a workaround to get this working with 2.x without needed to use a colab project?
> 
> ```
> # sudo pip3 install tensorflow==1.15.5
> ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.5 (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0)
> ERROR: No matching distribution found for tensorflow==1.15.5
> # python --version
> Python 3.9.2
> ```

sure, take a look at this comment https://github.com/NVIDIA/tacotron2/issues/558#issuecomment-1110826708
there's you may find some solution how to use tf2 with tacotron2.

Also there's installation steps of tf2 using pip https://www.tensorflow.org/install/pip
and from the source code https://www.tensorflow.org/install/source

And please send your pip version.
Write if the problem was solved or there're other problems.

**Comment by ruapotato** [comment]
@postovalov 
```
pip 20.3.4 from /home/david/.local/lib/python3.9/site-packages/pip (python 3.9)
david@debian-tv:~$ python3 --version
Python 3.9.2
````
I aslo tested with Debian 10, but that uses python 3.7 which is too old. It seem the only version of python that supports the pip libs is python 3.8? 

I don't want to use Google servers to convert your code (Aka colab) and I wont touch it.   `TF 1.x code to TF 2.x`  is a colab project.  I'm looking for a local solution.  
The problem is I cannot run this on a modern Linux system or an old one.

**Comment by postovalov** [comment]
> @postovalov
> 
> ```
> pip 20.3.4 from /home/david/.local/lib/python3.9/site-packages/pip (python 3.9)
> david@debian-tv:~$ python3 --version
> Python 3.9.2
> ```
pip 20.3.4 seems to work correct with tf2.
> I aslo tested with Debian 10, but that uses python 3.7 which is too old. It seem the only version of python that supports the pip libs is python 3.8?

Also python 2.7 & 3.7 is on the board on Debian Buster (Debian 10) https://wiki.debian.org/Python.
And tf2 software requirements is python 3.7-3.10 https://www.tensorflow.org/install/pip.
Everything seems like your setup should work.

> I don't want to use Google servers to convert your code (Aka colab) and I wont touch it. `TF 1.x code to TF 2.x` is a colab project. I'm looking for a local solution. The problem is I cannot run this on a modern Linux system or an old one.

Rewriting TF 1.x and compat.v1 API symbols isn't just about using the colab script. Please have a look at this description https://www.tensorflow.org/guide/migrate/upgrade.
It is possible to download this script to local storage from:
GitHub https://github.com/tensorflow/docs/blob/master/site/en/guide/migrate/upgrade.ipynb?utm_source=www.tensorflow.org&utm_medium=referral
Or directly https://storage.googleapis.com/tensorflow_docs/docs/site/en/guide/migrate/upgrade.ipynb?utm_source=www.tensorflow.org&utm_medium=referral

To streamline the changes, and to make your transition to TF 2.x as seamless as possible, the TensorFlow team has created the tf_upgrade_v2 utility to help transition legacy code to the new API.
Open the jupyter notebook in a terminal using ```jupyter notebook``` command, find and open the upgrade.ipynb file and follow the instructions.

If for some reason you cannot use jupyter notebook on your machine, then most commands from upgrade.ipynb can be executed directly in the terminal (these commands start with ```!``` in a cells (rows/lines)).

**Comment by ruapotato** [comment]
Getting tf1 running is beyond me. On debian 10 I get as far as:
```
root@old:/home/david/wwdd/voice/clean/tacotron2# pip3 install tensorflow==1.15.2
Collecting tensorflow==1.15.2
  Could not find a version that satisfies the requirement tensorflow==1.15.2 (from versions: 1.13.1, 1.13.2, 1.14.0)
No matching distribution found for tensorflow==1.15.2
root@old:/home/david/wwdd/voice/clean/tacotron2# python3 --version
Python 3.7.3
root@old:/home/david/wwdd/voice/clean/tacotron2# pip3 --version
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)
```
I'll wait for the update to run this on tf2. It was already a nightmare converting all the Jupiter notebooks I have had to use already. I wonder why people find `!CMD` is so much better than `os.system("CMD")` when that could mean the difference in general compatibility. 😕

**Comment by yxong05** [comment]
you can store the hparams as a dictionary instead: so,

hparams = {
        'epochs':500,
        'iters_per_checkpoint':1000,
        'seed':1234,
        'dynamic_loss_scaling':True,
        'fp16_run':False,
        'distributed_run':False,
        'dist_backend':"nccl",
        'dist_url':"tcp://localhost:54321",
        'cudnn_enabled':True,
        'cudnn_benchmark':False,
        'ignore_layers':['embedding.weight'],
...

and then change hparams.whatYouAreReferencing to hparams['whatYouAreReferencing']
