### ISSUE TITLE
Distributed training error

### ISSUE THREAD

**Issue by deli666** [NVIDIA/tacotron2#57]
When I train the model with 
"python -m multiproc train.py --output_directory=outdir --log_directory=logdir --hparams=distributed_run=True,fp16_run=True"

I got this error:
Traceback (most recent call last):
  File "/export/gpudata/deli/env/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/export/gpudata/deli/env/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/export/docker/JXQ-23-46-49.h.chinabank.com.cn/deli/tacotron2/multiproc.py", line 15, in <module>
    stdout = None if i == 0 else open("logs/{}_GPU_{}.log".format(job_id, i), "w")
FileNotFoundError: [Errno 2] No such file or directory: 'logs/2018_07_10-102521_GPU_1.log'

This error occurs when running multiproc.py. And the traning process hangs after showing:
Initializing distributed.

I checked the multiproc.py code and find that that file should be created by the code. Is there anywhere goes wrong?

Any help would be appreciated.

**Comment by deli666** [comment]
Hi, @NewEricWang 
No, I didn't. Do I need to make directory manually?

**Comment by deli666** [comment]
Thanks! @NewEricWang  It works now.
