### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by hejinlong** [NVIDIA/tacotron2#592]
Error: metadata-generation-failed

How to fix that?

```

(py38) long@System-Product-Name:~/tts/tacotron2$ pip install -r requirements.txt
Looking in indexes: http://mirrors.cloud.tencent.com/pypi/simple
Collecting matplotlib==2.1.0
  Using cached http://mirrors.cloud.tencent.com/pypi/packages/6c/90/cf10bb2020d2811da811a49601f6eafcda022c6ccd296fd05aba093dee96/matplotlib-2.1.0.tar.gz (35.7 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [2.1.0]
                      python: yes [3.8.16 (default, Mar  2 2023, 03:21:46)  [GCC
                              11.2.0]]
                    platform: yes [linux]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.17.5]
                         six: yes [using six version 1.16.0]
                    dateutil: yes [using dateutil version 2.8.2]
      backports.functools_lru_cache: yes [Not required]
                subprocess32: yes [Not required]
                        pytz: yes [using pytz version 2022.7.1]
                      cycler: yes [using cycler version 0.10.0]
                     tornado: yes [using tornado version 6.2]
                   pyparsing: yes [using pyparsing version 3.0.9]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [pkg-config information for 'libpng' could not
                              be found.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                      macosx: no  [Mac OS-X only]
                      qt5agg: no  [PySide2 not found; PyQt5 not found]
                      qt4agg: no  [PySide not found; PyQt4 not found]
                     gtk3agg: no  [Requires pygobject to be installed.]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-e49hwl5b/matplotlib_5942c83fef5a47dfb5196468db76bb08/setup.py", line 216, in <module>
          pkg_help = pkg.install_help_msg()
        File "/tmp/pip-install-e49hwl5b/matplotlib_5942c83fef5a47dfb5196468db76bb08/setupext.py", line 595, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
                   gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                      gtkagg: no  [Requires pygtk]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                       wxagg: no  [requires wxPython]
                         gtk: no  [Requires pygtk]
                         agg: yes [installing]
                       cairo: no  [cairocffi or pycairo not found]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL LATEX DEPENDENCIES
                      dvipng: no
                 ghostscript: yes [version 9.55.0]
                       latex: no
                     pdftops: yes [version 22.02.0]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`
```

**Comment by bhvym-sudo** [comment]
I am also facing same issues, do you find the solution yet?
