### ISSUE TITLE
Please mention that Python3.11 is not supported (by numba package)

### ISSUE THREAD

**Issue by AutonomousCat** [NVIDIA/tacotron2#597]
Having built a lot of stuff from source, I went through a lot to be met with this error. 

```
Collecting numba>=0.32 (from resampy>=0.2.0->librosa==0.6.0->-r requirements.txt (line 3))
  Downloading numba-0.56.4.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-94avnyh1/numba_1276963eca1146aa897a87b676b8f1b5/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-94avnyh1/numba_1276963eca1146aa897a87b676b8f1b5/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3.11 are supported.
      [end of output]
```

**Comment by a897456** [comment]
The author should have told us in advance, what version of python for this project
