### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by andrewb-ms** [NVIDIA/tacotron2#60]
**python train.py --output_directory=outdir --log_directory=logdir**
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "train.py", line 15, in <module>
    from model import Tacotron2
  File "/home/adm101/tacotron2/model.py", line 5, in <module>
    from layers import ConvNorm, LinearNorm
  File "/home/adm101/tacotron2/layers.py", line 2, in <module>
    from librosa.filters import mel as librosa_mel_fn
  File "/anaconda/envs/py35/lib/python3.5/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/anaconda/envs/py35/lib/python3.5/site-packages/librosa/core/__init__.py", line 102, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/anaconda/envs/py35/lib/python3.5/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/anaconda/envs/py35/lib/python3.5/site-packages/librosa/util/__init__.py", line 70, in <module>
    from . import decorators
  File "/anaconda/envs/py35/lib/python3.5/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
  File "/anaconda/envs/py35/lib/python3.5/site-packages/numba/__init__.py", line 12, in <module>
    from .special import typeof, prange
  File "/anaconda/envs/py35/lib/python3.5/site-packages/numba/special.py", line 4, in <module>
    from .parfor import prange
  File "/anaconda/envs/py35/lib/python3.5/site-packages/numba/parfor.py", line 23, in <module>
    from numba import array_analysis, postproc, typeinfer
  File "/anaconda/envs/py35/lib/python3.5/site-packages/numba/array_analysis.py", line 26, in <module>
    from numba.extending import intrinsic
  File "/anaconda/envs/py35/lib/python3.5/site-packages/numba/extending.py", line 15, in <module>
    from .pythonapi import box, unbox, reflect, NativeValue
  File "/anaconda/envs/py35/lib/python3.5/site-packages/numba/pythonapi.py", line 14, in <module>
    from numba import types, utils, cgutils, lowering, _helperlib
ImportError: numpy.core.multiarray failed to import

**Comment by danindiana** [comment]
I am getting this error too: "RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb"

What is the fix for this issue? 

 merlin@merlin-desktop
 OS: Ubuntu 18.04 bionic
 Kernel: x86_64 Linux 4.15.0-58-generic
 Uptime: 2h 0m
 Packages: 1981
 Shell: bash 4.4.20
 Resolution: 1920x1080 1080x1920
 DE: LXDE
 WM: OpenBox

**Comment by Yeongtae** [comment]
Removing numpy=1.13.0 in requirement.txt
Re install all on new conda env.
