### ISSUE TITLE
Why did I report this error and what should I do

### ISSUE THREAD

**Issue by hu-ye-yu** [NVIDIA/tacotron2#611]
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: False
cuDNN Enabled: True
cuDNN Benchmark: False
Warm starting model from checkpoint 'tacotron2_statedict.pt'
Epoch: 0
Traceback (most recent call last):
  File "train.py", line 291, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 208, in train
    for i, batch in enumerate(train_loader):
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/s1home/hyy523/tacotron2/tacotron2/data_utils.py", line 61, in __getitem__
    return self.get_mel_text_pair(self.audiopaths_and_text[index])
  File "/s1home/hyy523/tacotron2/tacotron2/data_utils.py", line 34, in get_mel_text_pair
    mel = self.get_mel(audiopath)
  File "/s1home/hyy523/tacotron2/tacotron2/data_utils.py", line 49, in get_mel
    melspec = torch.from_numpy(np.load(filename))
  File "/home/hyy523/anaconda3/envs/tacotron2/lib/python3.6/site-packages/numpy/lib/npyio.py", line 457, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False

**Comment by a897456** [comment]
Try the pre-trianed modle order directly after you have download the pre-trained modle：python train.py --output_directory=outdir --log_directory=logdir -c tacotron2_statedict.pt --warm_start

**Comment by a897456** [comment]
chinese?work together?weixin?
