### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by begeekmyfriend** [NVIDIA/tacotron2#74]
When I tried on single GPU, it works. But now I have multi-gpu, it threw an exception. Please help!
```python
hparams = create_hparams("distributed_run=False,mask_padding=False")
model = load_model(hparams)
checkpoint_path="outputs/checkpoint_18000"
model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})
```
```shell
Traceback (most recent call last):
  File "synthesize.py", line 15, in <module>
    model.load_state_dict({k.replace('module.',''):v for k,v in torch.load(checkpoint_path)['state_dict'].items()})
  File "/home/leoma/miniconda3/envs/tensorflow/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.embedding.weight", "module.encoder.convolutions.0.0.conv.weight", "module.encoder.convolutions.0.0.conv.bias", "module.encoder.convolutions.0.1.weight", "module.encoder.convolutions.0.1.bias", "module.encoder.convolutions.0.1.running_mean", "module.encoder.convolutions.0.1.running_var", "module.encoder.convolutions.1.0.conv.weight", "module.encoder.convolutions.1.0.conv.bias", "module.encoder.convolutions.1.1.weight", "module.encoder.convolutions.1.1.bias", "module.encoder.convolutions.1.1.running_mean", "module.encoder.convolutions.1.1.running_var", "module.encoder.convolutions.2.0.conv.weight", "module.encoder.convolutions.2.0.conv.bias", "module.encoder.convolutions.2.1.weight", "module.encoder.convolutions.2.1.bias", "module.encoder.convolutions.2.1.running_mean", "module.encoder.convolutions.2.1.running_var", "module.encoder.lstm.weight_ih_l0", "module.encoder.lstm.weight_hh_l0", "module.encoder.lstm.bias_ih_l0", "module.encoder.lstm.bias_hh_l0", "module.encoder.lstm.weight_ih_l0_reverse", "module.encoder.lstm.weight_hh_l0_reverse", "module.encoder.lstm.bias_ih_l0_reverse", "module.encoder.lstm.bias_hh_l0_reverse", "module.decoder.prenet.layers.0.linear_layer.weight", "module.decoder.prenet.layers.1.linear_layer.weight", "module.decoder.attention_rnn.weight_ih", "module.decoder.attention_rnn.weight_hh", "module.decoder.attention_rnn.bias_ih", "module.decoder.attention_rnn.bias_hh", "module.decoder.attention_layer.query_layer.linear_layer.weight", "module.decoder.attention_layer.memory_layer.linear_layer.weight", "module.decoder.attention_layer.v.linear_layer.weight", "module.decoder.attention_layer.location_layer.location_conv.conv.weight", "module.decoder.attention_layer.location_layer.location_dense.linear_layer.weight", "module.decoder.decoder_rnn.weight_ih", "module.decoder.decoder_rnn.weight_hh", "module.decoder.decoder_rnn.bias_ih", "module.decoder.decoder_rnn.bias_hh", "module.decoder.linear_projection.linear_layer.weight", "module.decoder.linear_projection.linear_layer.bias", "module.decoder.gate_layer.linear_layer.weight", "module.decoder.gate_layer.linear_layer.bias", "module.postnet.convolutions.0.0.conv.weight", "module.postnet.convolutions.0.0.conv.bias", "module.postnet.convolutions.0.1.weight", "module.postnet.convolutions.0.1.bias", "module.postnet.convolutions.0.1.running_mean", "module.postnet.convolutions.0.1.running_var", "module.postnet.convolutions.1.0.conv.weight", "module.postnet.convolutions.1.0.conv.bias", "module.postnet.convolutions.1.1.weight", "module.postnet.convolutions.1.1.bias", "module.postnet.convolutions.1.1.running_mean", "module.postnet.convolutions.1.1.running_var", "module.postnet.convolutions.2.0.conv.weight", "module.postnet.convolutions.2.0.conv.bias", "module.postnet.convolutions.2.1.weight", "module.postnet.convolutions.2.1.bias", "module.postnet.convolutions.2.1.running_mean", "module.postnet.convolutions.2.1.running_var", "module.postnet.convolutions.3.0.conv.weight", "module.postnet.convolutions.3.0.conv.bias", "module.postnet.convolutions.3.1.weight", "module.postnet.convolutions.3.1.bias", "module.postnet.convolutions.3.1.running_mean", "module.postnet.convolutions.3.1.running_var", "module.postnet.convolutions.4.0.conv.weight", "module.postnet.convolutions.4.0.conv.bias", "module.postnet.convolutions.4.1.weight", "module.postnet.convolutions.4.1.bias", "module.postnet.convolutions.4.1.running_mean", "module.postnet.convolutions.4.1.running_var". 
	Unexpected key(s) in state_dict: "embedding.weight", "encoder.convolutions.0.0.conv.weight", "encoder.convolutions.0.0.conv.bias", "encoder.convolutions.0.1.weight", "encoder.convolutions.0.1.bias", "encoder.convolutions.0.1.running_mean", "encoder.convolutions.0.1.running_var", "encoder.convolutions.1.0.conv.weight", "encoder.convolutions.1.0.conv.bias", "encoder.convolutions.1.1.weight", "encoder.convolutions.1.1.bias", "encoder.convolutions.1.1.running_mean", "encoder.convolutions.1.1.running_var", "encoder.convolutions.2.0.conv.weight", "encoder.convolutions.2.0.conv.bias", "encoder.convolutions.2.1.weight", "encoder.convolutions.2.1.bias", "encoder.convolutions.2.1.running_mean", "encoder.convolutions.2.1.running_var", "encoder.lstm.weight_ih_l0", "encoder.lstm.weight_hh_l0", "encoder.lstm.bias_ih_l0", "encoder.lstm.bias_hh_l0", "encoder.lstm.weight_ih_l0_reverse", "encoder.lstm.weight_hh_l0_reverse", "encoder.lstm.bias_ih_l0_reverse", "encoder.lstm.bias_hh_l0_reverse", "decoder.prenet.layers.0.linear_layer.weight", "decoder.prenet.layers.1.linear_layer.weight", "decoder.attention_rnn.weight_ih", "decoder.attention_rnn.weight_hh", "decoder.attention_rnn.bias_ih", "decoder.attention_rnn.bias_hh", "decoder.attention_layer.query_layer.linear_layer.weight", "decoder.attention_layer.memory_layer.linear_layer.weight", "decoder.attention_layer.v.linear_layer.weight", "decoder.attention_layer.location_layer.location_conv.conv.weight", "decoder.attention_layer.location_layer.location_dense.linear_layer.weight", "decoder.decoder_rnn.weight_ih", "decoder.decoder_rnn.weight_hh", "decoder.decoder_rnn.bias_ih", "decoder.decoder_rnn.bias_hh", "decoder.linear_projection.linear_layer.weight", "decoder.linear_projection.linear_layer.bias", "decoder.gate_layer.linear_layer.weight", "decoder.gate_layer.linear_layer.bias", "postnet.convolutions.0.0.conv.weight", "postnet.convolutions.0.0.conv.bias", "postnet.convolutions.0.1.weight", "postnet.convolutions.0.1.bias", "postnet.convolutions.0.1.running_mean", "postnet.convolutions.0.1.running_var", "postnet.convolutions.1.0.conv.weight", "postnet.convolutions.1.0.conv.bias", "postnet.convolutions.1.1.weight", "postnet.convolutions.1.1.bias", "postnet.convolutions.1.1.running_mean", "postnet.convolutions.1.1.running_var", "postnet.convolutions.2.0.conv.weight", "postnet.convolutions.2.0.conv.bias", "postnet.convolutions.2.1.weight", "postnet.convolutions.2.1.bias", "postnet.convolutions.2.1.running_mean", "postnet.convolutions.2.1.running_var", "postnet.convolutions.3.0.conv.weight", "postnet.convolutions.3.0.conv.bias", "postnet.convolutions.3.1.weight", "postnet.convolutions.3.1.bias", "postnet.convolutions.3.1.running_mean", "postnet.convolutions.3.1.running_var", "postnet.convolutions.4.0.conv.weight", "postnet.convolutions.4.0.conv.bias", "postnet.convolutions.4.1.weight", "postnet.convolutions.4.1.bias", "postnet.convolutions.4.1.running_mean", "postnet.convolutions.4.1.running_var". 
```

**Comment by begeekmyfriend** [comment]
Hey, I solved this problem by type
> CUDA_VISIBLE_DEVICES=0 python synthesize.py

Now I can synthesize Chinease mandarin on this version!
[test.zip](https://github.com/NVIDIA/tacotron2/files/2313929/test.zip)

**Comment by begeekmyfriend** [comment]
I used single GPU with batch size as 32 and reduction factor as 2. The synthesizer is G&L and my fork is [here](https://github.com/begeekmyfriend/Tacotron-2). and here is my latest results. https://github.com/keithito/tacotron/issues/118#issuecomment-428421472
Of course I recommend T2.

**Comment by candlewill** [comment]
Thanks.

**Comment by tsungruihon** [comment]
您好 想问下您有试过在中文语料上尝试过这个项目吗？

**Comment by begeekmyfriend** [comment]
@tsungruihon https://github.com/NVIDIA/tacotron2/issues/74#issuecomment-415361078
