### ISSUE TITLE
insufficient shared memory

### ISSUE THREAD

**Issue by DHOFM** [NVIDIA/tacotron2#77]
Hi,
I tried to train on a Google Cloud VM with K 80 in colab. I lowered batch_size to 36 because it´s only one GPU with almost 12 GB, so in fact it´s "half" card. That works so far. But after iteration 2000 memory fails. In Colab it´s a Docker container afaik. So here a the specs before starting to train:
**Gen RAM Free: 12.6 GB  | Proc size: 141.3 MB
GPU RAM Free: 11439MB | Used: 0MB | Util   0% | Total 11439MB**
 
So training will fail with the following exceptions:
`Train loss 2000 0.866389 Grad Norm 0.812214 11.32s/it
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
�train.py:144: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  if distributed_run else loss.data[0]
Traceback (most recent call last):
  File "train.py", line 291, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 244, in train
    n_gpus, collate_fn, logger, hparams.distributed_run, rank)
  File "train.py", line 139, in validate
    for i, batch in enumerate(val_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 280, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 259, in _get_batch
   return self.data_queue.get()
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 70, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused`

The first three checkpoints 500 to 1500 are saved anyway. Any changes to parameters to make it work ??? 

Kind regards,

Dirk

**Comment by marshgammon** [comment]
Are you using a docker container? 
Try setting a higher shared memory amount with the `--shm-size 10G` to the `docker run` command

**Comment by rafaelvalle** [comment]
Closing due to inactivity.
