### ISSUE TITLE
NCCL error in distributed run: unhandled cuda error

### ISSUE THREAD

**Issue by Worldexe** [NVIDIA/tacotron2#98]
I have the following error while trying to run distributed setup:

The commands are these:
```
python3.6 train.py \
			--n_gpus=2 \
			--rank=0 \
			--output_directory=outdir_en_22 \
			--log_directory=logdir \
			--hparams=batch_size=$batch_size,distributed_run=True,dist_backend="nccl",dist_url="tcp://localhost:54321" &
python3.6 train.py \
			--n_gpus=2 \
			--rank=1 \
			--output_directory=outdir_en_22 \
			--log_directory=logdir \
			--hparams=batch_size=$batch_size,distributed_run=True,dist_backend="nccl",dist_url="tcp://localhost:54321" &
```

Other hparams are default (as in master).
The error is the same if I use file:// or tcp:// distributed urls.

The log is:
```
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing Distributed
Done initializing distributed
FP16 Run: False
Dynamic Loss Scaling: True
Distributed Run: True
cuDNN Enabled: True
cuDNN Benchmark: False
Initializing Distributed
Done initializing distributed
Traceback (most recent call last):
  File "train.py", line 294, in <module>
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
  File "train.py", line 179, in train
Traceback (most recent call last):
    model = load_model(hparams)
  File "train.py", line 294, in <module>
  File "train.py", line 87, in load_model
    args.warm_start, args.n_gpus, args.rank, args.group_name, hparams)
    model = apply_gradient_allreduce(model)
  File "train.py", line 179, in train
  File "/home/ttsynth/tacotron2-nvidia-new/tacotron2/distributed.py", line 135, in apply_gradient_allreduce
    model = load_model(hparams)
    dist.broadcast(p, 0)
  File "train.py", line 87, in load_model
  File "/home/ttsynth/tacotron2-nvidia-new/tacotron2/p3.6_venv/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 723, in broadcast
    model = apply_gradient_allreduce(model)
    work = _default_pg.broadcast([tensor], opts)
  File "/home/ttsynth/tacotron2-nvidia-new/tacotron2/distributed.py", line 135, in apply_gradient_allreduce
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:252, unhandled cuda error
    dist.broadcast(p, 0)
  File "/home/ttsynth/tacotron2-nvidia-new/tacotron2/p3.6_venv/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 723, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:252, unhandled cuda error
```

The platform is Linux, Ubuntu 16, python3.6; I installed pytorch 1.0.0 from nightly build just today; I am using 1080 cards. tacotron2 repo was updated just now, on master.

What can be wrong? Is it pytorch bug?

**Comment by Worldexe** [comment]
For those who encounter the same error: you really need to use `python -m multiproc train.py ...` instead of just `python train.py ...`. Still, the error message is very misleading :(
